language: node_js
node_js: stable
script:
- npm run test:lint
- polymer test --skip-plugin local
addons:
  sauce_connect: true
  jwt:
    # SAUCE_ACCESS_KEY
    secure: X7WmL5qs53zE9L83xMi/vstkmsbrRAzYAtPMpM1noy+++iGeiAqGdBSORB5pz/UGWUnktn/GwXH/GmUwJY3ErKZPpaF9G8N1olG+c9a50xhmjtfGSNLjjESfRpPXMB0W/FYgymdKLN94di71usKSdkJQ6ex2lJAcUBZfp2loFQY=
env:
  global:
    # SAUCE_USERNAME
    secure: Q9E/CWS1ADQHYPZ5MZzz2Damk/FhRaykISX7HCGywhcRYri79O2hGGb04MEvWxB5NTTUi9nqvNTDZ2+atyiCC/whTQ/uIt+rAEBaATUNDnVEUdcj0m7O5jsuHvIzaKsi7FaXvghD/hx82qm6HmxfSNfb456LBh3rKil/PqZSAUs=
