language: node_js
node_js: stable
before_script:
- gem install percy-cli
script:
- polylint
after_success:
- '[ "$TRAVIS_SECURE_ENV_VARS" = "true" ] && npm run perceptual-diff'
sudo: false
addons:
  sauce_connect:
    username:
      secure: "UY9DQ7X3kuNXsmm/PqNvigMEqFdEIkIimJ9FP6y/4cE+eVfdxCB0Y3r8m2tw4++zU6p5xD1TK84haaOsGSb7Y0pEYISdUnRiZ8epiJq9fhu3E8WyvCOERMdp5fNaOxtBCYZdFdMPPMq9AD5yatmVgFP8i8zbB+7n+HxbsOPujrQ="
    access_key:
      secure: "YZrQF4IFxPiBLCvGywNoe+dgvjqozqsWVqNnqnE3ez99OWRk/7LH29Gj81/HASJlhMuLBBC0qG2OLekuKQuozn/tSy4nvVzrXjjbs3mlAKrOWPWC+cZVINusUBBoMu0L4zxixxVebh179dLT+/vzD/UXyqlDEPBlnZqVMP7eDTQ="
env:
  global:
    secure: DLla5yS0KINkxAGk5xBcBShCpuW5BybW4CSPcBOrjQTmAryc45kIJudiimggZRpAjSsDAsIE/5bTrRbYdadzrq7ytsi4RoC0nZUli2TTCtx/j0F1wAAl6kVfK2njRrWPbqFl+8vp8kzyPqW+7esAy0xuoNqAGAAD5wK+5noZv3Y=
