language: node_js
node_js:
- '0.10'
before_install:
- export COMMIT_SHA=`git log -1 --pretty=format:%H`
- npm config set always-auth true
- npm config set _auth $NPM_AUTH
- npm config set email $NPM_EMAIL
deploy:
  provider: npm
  email: $NPM_EMAIL
  skip_cleanup: true
  api_key:
    secure: P6vYOAG8gAXcN7HFy8ZCSQkS5uAYbA4gYGNwTEbEP+e9I2s6UxiqEPk4kSHRY+M+cxZbPquB0I1GKxaptTJZHpHPAAdZwcfGORK/b0VlzMXKp6rY8jG1ofCLLxDt9596oQDubiWgp0mTc1uqO4+YekXIKuS1nmTrSnTFiL5sqIw=
  on:
    all_branches: true
    tags: true
env:
  global:
    - NPM_EMAIL=dave.lockhart@d2l.com
    - secure: r7VbkCi4MFHQqE409cOuoYce2csTXqsEdd2gl3LjDitgLWzBHMmhXXY7A9iMnZEax28KvdSRDYKUB6xEm6+6L7CsTDgmsu5qla7v9/vjCd68ljriwO+wrRvtXuq5ICyQ+jTO/wWMd4dO4QnA3u9+yP+wAeyJMvUhhNnFFEVHO2A=

