language: node_js
node_js:
- '0.12'
sudo: false
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: WGEuoW637XOPrLRk4UF/BC65RpaLwAXDKtCBXW2aMOm7o6Ncv/CvLLkAIoUvG4cjMSOOkOt3oI3T63Dz7w5eNlzn14u5RcT3OsIZDwfNdS1nnASL+kOW48X4MDNZa2FEKR9//LQN38RqnNf30jeTQV/shYiqlLK1fa034kguqFI=
  on:
    tags: true
    repo: Brightspace/valence-ui-button
