language: node_js
node_js: stable
before_script:
- gem install percy-cli
script:
- polylint
after_success:
- '[ "$TRAVIS_SECURE_ENV_VARS" = "true" ] && npm run perceptual-diff'
sudo: false
addons:
  sauce_connect:
    username:
      secure: "DIyMRPX30LXS79iLqPiXUw597gUiPdxCFED1S02ZgFgFyH2w/MvFlWh3M80kLespyM8g/h2KuBoxMtHDHqhB8LQy8Cr+RJdq8LxhwRAAAQX4oTbrvVODS62m8zMUhbl0d8EuCVW2+kDkIEemOPKCRim9XgaFbCuXrEwtTocrTSo="
    access_key:
      secure: "ca3LzyTtiYEaejlPRt+50LpeZ0c3bIytW/EhDE57VKWiGRHpYaybJAdW5WQaYV19j9ZrOCGOOyZXldKCRhw0OEfNikc1MliHxXapArPrnSU7qUm23f2Bi1sI8UdGqZsS3N66JN1NS2HeoSTZJcq/ZzkSNJt/JgwPKA+PyOdIY0Y="
env:
  global:
    secure: DLla5yS0KINkxAGk5xBcBShCpuW5BybW4CSPcBOrjQTmAryc45kIJudiimggZRpAjSsDAsIE/5bTrRbYdadzrq7ytsi4RoC0nZUli2TTCtx/j0F1wAAl6kVfK2njRrWPbqFl+8vp8kzyPqW+7esAy0xuoNqAGAAD5wK+5noZv3Y=
